name: test

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: |
          rm -f coverage.out coverage.out.tmp
          go clean -testcache
          go test ./... -v -race -failfast -coverprofile coverage.out -covermode=atomic
          go tool cover -func coverage.out

        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella